// flow-typed signature: 9ef93bfb85f333836c27f134ba47b247
// flow-typed version: <<STUB>>/koa-jwt_v^1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-jwt/test-server' {
  declare module.exports: any;
}

declare module 'koa-jwt/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-jwt/index' {
  declare module.exports: $Exports<'koa-jwt'>;
}
declare module 'koa-jwt/index.js' {
  declare module.exports: $Exports<'koa-jwt'>;
}
declare module 'koa-jwt/test-server.js' {
  declare module.exports: $Exports<'koa-jwt/test-server'>;
}
declare module 'koa-jwt/test.js' {
  declare module.exports: $Exports<'koa-jwt/test'>;
}
